### ISSUE TITLE
Create AddRecordActivity

### ISSUE THREAD

**Issue by ImJoeYouKnow** [CMPUT301F18T19/HADA#41]
This is the activity that the user sees when they choose to create a new record while viewing a problem.
Elements include:
 - "Add Record" title
 - Preview of optional attached image
 - add comment field
 - select photos button
 - save geo location toggle switch

It should [look something like this.](https://drive.google.com/file/d/1Xza_Tm8q1lrhpH-cASge-7fEvbtSx3Fp/view?usp=sharing)

**Comment by capenner** [comment]
Completed basic XML and buttons for AddRecordActivity
