### ISSUE TITLE
Old feedback

### ISSUE THREAD

**Issue by ColonelSanders21** [CMPUT301F18T19/HADA#98]
Old Feedback
1. Wrong usecase nameS e.g. PatientEditProblem, PatientDeleteProblem NOT ADDRESSED!
1. Doesn't show mockups separately, missing use case  scenarios NOT ADDRESSED BUT IT'S FINE.
2. Very bad way to present mockups NOT ADDRESSED SOME NAVIGATION STILL MISSING.
4. Add WOW Factor NOT ADDRESSED - NEED DETAILED DESCRIPTION OF WHAT YOU WILL DO.

**Comment by capenner** [comment]
Don't have access to mockups but I have fixed the wiki
